# Generated by Django 2.0.5 on 2018-05-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('com', 'complete'), ('incom', 'incomplete'), ('to', 'todo')], default='to', max_length=16),
        ),
    ]
